def generate_section_1():
    return """# 1. FULL REPOSITORY MAP

## 1.1 Complete Folder and File Tree
Below is the exhaustive, file-by-file inventory of every file in the SolarGrid repository, with a concrete one-line statement of its architectural purpose.

| File Path | Primary Architectural Purpose |
| :--- | :--- |
| `/.env` | Local environment configuration storing Supabase URL, anon key, service role key, and cycle defaults. |
| `/.eslintrc.json` | ESLint configuration extending `next/core-web-vitals` for static code analysis. |
| `/PRODUCTION_AUDIT.md` | Legacy pre-remediation gap analysis and status scorecard dated August 24, 2026. |
| `/middleware.ts` | Next.js Edge middleware routing requests to Supabase session validator and route guard. |
| `/next-env.d.ts` | Auto-generated Next.js TypeScript declarations for compiler support. |
| `/next.config.mjs` | Next.js build and runtime configuration with remote image domain wildcard patterns. |
| `/package.json` | Node.js project manifest defining runtime/dev dependencies, scripts, and package metadata. |
| `/package-lock.json` | Deterministic dependency tree lockfile recording exact installed package versions. |
| `/postcss.config.mjs` | PostCSS pipeline configuration loading TailwindCSS and Autoprefixer plugins. |
| `/tailwind.config.ts` | Tailwind CSS configuration defining custom Midnight Solar color tokens, glow shadows, and animations. |
| `/tsconfig.json` | TypeScript compiler configuration specifying ESNext target, strict mode, and `@/*` path alias. |
| `/tsconfig.tsbuildinfo` | Incremental compilation cache generated by the TypeScript compiler. |
| `/vitest.config.ts` | Vitest testing framework configuration defining Node environment and path aliases. |
| `/types/index.ts` | Central TypeScript interfaces and domain types for users, solar plans, ledger, sessions, and tickets. |
| `/database/schema.sql` | Full PostgreSQL DDL schema with 19 tables, indexes, constraints, and Supabase RLS policies. |
| `/database/migrations/` | Directory intended for versioned SQL migrations (currently empty). |
| `/scripts/inventory.js` | Node.js file discovery script that enumerates pages, API routes, layouts, and components. |
| `/scripts/seed-demo-users.ts` | Database seeding script provisioning Super Admin (`marcus.vance@solargrid.io`) and User (`sarah.jenkins@solargrid.io`). |
| `/public/images/panel-p1.jpg` | Visual asset render for the P1 Solar Starter (0.5 kW) hardware package. |
| `/public/images/panel-p2.jpg` | Visual asset render for the P2 Solar Growth (1.2 kW) commercial array package. |
| `/public/images/panel-p3.jpg` | Visual asset render for the P3 Solar Pro (3.5 kW) industrial solar farm unit. |
| `/public/images/solar-desert-park.png` | Marketing asset representing Sonoran Solar Basin desert facility. |
| `/public/images/solar-farm-hero.png` | High-resolution landing page hero banner depicting utility-scale solar matrix. |
| `/public/images/solar-floating.png` | Marketing asset representing Atacama Horizon floating photovoltaic complex. |
| `/public/images/solar-rooftop.png` | Marketing asset representing Bavarian Agrivoltaic Microgrid facility. |
| `/components/glass/glass-badge.tsx` | Glassmorphic badge pill component supporting multiple color variants (gold, amber, blue, emerald, slate). |
| `/components/glass/glass-bottom-bar.tsx` | Mobile-first floating bottom navigation dock with safe-area padding and active route highlighting. |
| `/components/glass/glass-button.tsx` | Reusable tactile glass button with gradient styling, hover lift, loading spinners, and size variants. |
| `/components/glass/glass-card.tsx` | Translucent glass surface container component with elevation tiers (glass-1, glass-2, glass-3). |
| `/components/glass/glass-chart-container.tsx` | Glass wrapper component designed for embedding Recharts interactive data visualization charts. |
| `/components/glass/glass-input.tsx` | Form input and textarea component styled with translucent backgrounds and golden focus rings. |
| `/components/glass/glass-navbar.tsx` | Top floating navigation pill for user dashboard with live notification badge and user initials. |
| `/components/glass/glass-sheet.tsx` | Modal dialog and bottom slide-over drawer component with backdrop blur and touch dismiss. |
| `/components/glass/glass-table.tsx` | Standardized dark glass data table container with custom scrollbars and hover row highlights. |
| `/components/glass/glass-tabs.tsx` | Segmented tab control component with animated sliding active indicator. |
| `/components/glass/index.ts` | Barrel export file bundling all glass design system components. |
| `/components/motion/lenis-provider.tsx` | Smooth-scrolling context provider wrapping application in Lenis smooth scroll engine. |
| `/components/ui/footer.tsx` | Comprehensive public marketing footer with platform links, copyright, and operational status ticker. |
| `/components/ui/navigation.tsx` | Public sticky marketing navigation bar with operational time ticker, links, and auth buttons. |
| `/components/ui/role-switcher.tsx` | Obsolete mock role switcher disabled in production architecture (returns null). |
| `/lib/auth/auth-context.tsx` | React client context providing user state, profile state, login, signup, logout, and token sync. |
| `/lib/auth/guards.ts` | Server-side authentication and RBAC guards (`requireAuthenticatedUser`, `requireSuperAdmin`, `enforceUserOwnership`). |
| `/lib/auth/transaction-pin.ts` | Bcrypt-hashed 6-digit transaction PIN verification, lockout tracker, and update handler. |
| `/lib/database/db.ts` | Deprecated mock database stub file alerting developers to use Supabase database layer. |
| `/lib/database/seed-data.ts` | Comprehensive static mock data and initial configuration constants for offline fallback. |
| `/lib/leadership-engine/index.ts` | Leadership rank progression engine calculating tier eligibility, requirements, and promotion bonuses. |
| `/lib/mlm-engine/index.ts` | Multi-Level Marketing 3-tier commission distribution engine with anti-cycle traversal. |
| `/lib/points-engine/index.ts` | Points economy engine calculating performance multipliers, point adjustments, and milestone redemptions. |
| `/lib/security/rate-limiter.ts` | In-memory sliding-window IP rate limiter protecting auth, financial, and admin endpoints. |
| `/lib/solar-engine/index.ts` | Core solar engine managing weekday schedules, daily operation state machines, and plan purchases. |
| `/lib/solar-engine/upgrade.ts` | Solar unit upgrade calculator and transaction executor computing trade-in credits. |
| `/lib/supabase/admin.ts` | Server-only Supabase client instance instantiated with `SUPABASE_SERVICE_ROLE_KEY`. |
| `/lib/supabase/client.ts` | Browser-side Supabase client instance instantiated with `NEXT_PUBLIC_SUPABASE_ANON_KEY`. |
| `/lib/supabase/db.ts` | Central database service layer wrapping Supabase PostgreSQL queries with type mappers. |
| `/lib/supabase/middleware.ts` | Session refreshing and edge route security middleware for Supabase SSR auth. |
| `/lib/supabase/server.ts` | Server component and API route Supabase client factory reading request cookies. |
| `/lib/withdrawal-engine/index.ts` | Withdrawal validation engine enforcing limits, calculating fees, and managing admin state transitions. |
| `/tests/auth-guards.test.ts` | Vitest test suite validating server-side route guards on member and admin API endpoints. |
| `/tests/business-logic.test.ts` | Vitest test suite validating MLM commissions, solar yields, points multipliers, and upgrade math. |
| `/tests/e2e-api-and-workflows.test.ts` | Vitest test suite validating end-to-end user journeys (recharge, purchase, operate, withdraw). |
| `/tests/security-auth.test.ts` | Vitest test suite validating password checks, token security, anti-IDOR, and double-refund prevention. |
| `/app/layout.tsx` | Root Next.js layout providing global HTML structure, fonts, AuthProvider, and Lenis smooth scrolling. |
| `/app/globals.css` | Global stylesheet defining Tailwind directives, custom glass utility classes, and fonts. |
| `/app/page.tsx` | Public landing page featuring hero section, live counters, solar plan cards, technology grid, and CTA. |
| `/app/about/page.tsx` | Public marketing page detailing company mission, green energy vision, and leadership executive team. |
| `/app/plans/page.tsx` | Public solar capacity catalog showcasing P1, P2, and P3 investment plans with yield calculator. |
| `/app/projects/page.tsx` | Public technology showcase detailing operational solar parks (Sonoran, Mojave, Atacama, Bavaria). |
| `/app/how-it-works/page.tsx` | Step-by-step interactive visual walkthrough explaining capital contribution and daily yield cycles. |
| `/app/rules/page.tsx` | Official operational rulebook detailing weekday hours (12-3 PM), fees, and anti-abuse policies. |
| `/app/contact/page.tsx` | Public customer support and corporate contact page with feedback submission form. |
| `/app/faq/page.tsx` | Frequently Asked Questions accordion page covering wallets, solar operation, MLM, and withdrawals. |
| `/app/privacy/page.tsx` | Standard GDPR and financial privacy policy disclosure document. |
| `/app/terms/page.tsx` | Platform Terms of Service and digital solar infrastructure participation agreement. |
| `/app/login/page.tsx` | User authentication screen with email/password validation, demo account presets, and error banners. |
| `/app/signup/page.tsx` | Account registration screen with name, email, password, confirm password, and referral code tracking. |
| `/app/forgot-password/page.tsx` | Password recovery request screen with email submission and instructions. |
| `/app/community/page.tsx` | Redirect stub routing `/community` to `/plans`. |
| `/app/leadership/page.tsx` | Redirect stub routing `/leadership` to `/plans`. |
| `/app/rewards/page.tsx` | Redirect stub routing `/rewards` to `/plans`. |
| `/app/dashboard/layout.tsx` | Authenticated user layout rendering GlassNavbar, main content container, and GlassBottomBar. |
| `/app/dashboard/page.tsx` | Primary member dashboard summarizing balances, daily operation widget, telemetry, and quick actions. |
| `/app/dashboard/panels/page.tsx` | Solar panel fleet management screen with performance cards and upgrade modals. |
| `/app/dashboard/panels/[id]/page.tsx` | Deep telemetry analysis screen for a single solar unit with interactive yield charts and operational log. |
| `/app/dashboard/panel-operation/page.tsx` | Interactive solar daily operation screen executing START -> Animation -> RECEIVE workflow. |
| `/app/dashboard/plans/page.tsx` | In-dashboard solar plan investment portal with purchase modals and balance validation. |
| `/app/dashboard/units/page.tsx` | Active solar hardware units dashboard with daily operation status and upgrade actions. |
| `/app/dashboard/earnings/page.tsx` | Detailed financial income breakdown separating daily generation, L1/L2/L3 commissions, and bonuses. |
| `/app/dashboard/recharge/page.tsx` | USDT crypto deposit screen with network selection, QR code deposit address, and proof upload form. |
| `/app/dashboard/withdrawal/page.tsx` | USDT withdrawal request screen with fee calculation, transaction PIN verification, and balance checks. |
| `/app/dashboard/withdrawals/page.tsx` | Legacy withdrawal request and history screen with active queue tabs. |
| `/app/dashboard/records/page.tsx` | Unified transaction records center with 10 filter tabs, search, date filtering, and CSV export. |
| `/app/dashboard/records/recharge/page.tsx` | Dedicated recharge deposit history screen with status badges and TX hash inspector. |
| `/app/dashboard/records/withdrawals/page.tsx` | Dedicated withdrawal request history screen with net payout amounts and status tracking. |
| `/app/dashboard/records/purchases/page.tsx` | Dedicated solar panel purchase and upgrade history ledger screen. |
| `/app/dashboard/notifications/page.tsx` | Member notification center with category filtering, mark-as-read actions, and link navigation. |
| `/app/dashboard/profile/page.tsx` | User profile management screen with personal information form, 2FA toggle, and password change modal. |
| `/app/dashboard/profile/wallet/page.tsx` | Secure wallet configuration screen requiring 6-digit transaction PIN to bind USDT address. |
| `/app/dashboard/support/page.tsx` | Member support center with ticket creation modal, priority selection, and live chat thread view. |
| `/app/dashboard/invite/page.tsx` | Redirect stub routing `/dashboard/invite` to `/dashboard`. |
| `/app/dashboard/network/page.tsx` | Redirect stub routing `/dashboard/network` to `/dashboard`. |
| `/app/dashboard/team/page.tsx` | Redirect stub routing `/dashboard/team` to `/dashboard`. |
| `/app/dashboard/referrals/page.tsx` | Redirect stub routing `/dashboard/referrals` to `/dashboard`. |
| `/app/dashboard/points/page.tsx` | Redirect stub routing `/dashboard/points` to `/dashboard`. |
| `/app/dashboard/rewards/page.tsx` | Redirect stub routing `/dashboard/rewards` to `/dashboard`. |
| `/app/dashboard/leadership/page.tsx` | Redirect stub routing `/dashboard/leadership` to `/dashboard`. |
| `/app/admin/layout.tsx` | Super Admin layout rendering desktop sidebar, mobile header/drawer, and role badge. |
| `/app/admin/page.tsx` | Admin executive command center with global KPI metrics, quick actions, and cross-platform search. |
| `/app/admin/analytics/page.tsx` | Administrative business intelligence screen with financial charts, growth metrics, and generation stats. |
| `/app/admin/users/page.tsx` | 360° user management table with status toggling, balance adjustments, and point modification modal. |
| `/app/admin/users/[id]/page.tsx` | Deep user profile audit screen detailing downline tree, units owned, financial ledger, and sessions. |
| `/app/admin/plans/page.tsx` | Solar plan price, yield, and fee editor with interactive parameter update forms. |
| `/app/admin/units/page.tsx` | Global solar hardware fleet monitor displaying all user-owned units and operating conditions. |
| `/app/admin/panel-images/page.tsx` | Solar panel visual asset manager allowing admins to update marketing image URLs and captions. |
| `/app/admin/recharges/page.tsx` | Financial recharge approval desk with TX hash verification, deposit review, and one-click balance crediting. |
| `/app/admin/withdrawals/page.tsx` | Financial withdrawal queue with approve, process, complete (with TX hash), and reject (with refund) actions. |
| `/app/admin/ledger/page.tsx` | Platform-wide immutable financial ledger audit log with transaction filtering and CSV export. |
| `/app/admin/security/sessions/page.tsx` | Device security monitoring desk tracking active sessions, IP addresses, user agents, and force revocation. |
| `/app/admin/broadcasts/page.tsx` | System-wide announcement dispatcher sending notifications targeted by audience tier. |
| `/app/admin/support/page.tsx` | Administrative support ticketing desk with message response composer and ticket status workflow. |
| `/app/admin/audit/page.tsx` | System security audit trail recording all administrative actions, targets, IPs, and timestamps. |
| `/app/admin/settings/page.tsx` | Platform business rule management portal for operating hours, commission rates, and minimum limits. |
| `/app/admin/leadership/page.tsx` | Redirect stub routing `/admin/leadership` to `/admin/plans`. |
| `/app/admin/mlm/page.tsx` | Redirect stub routing `/admin/mlm` to `/admin/plans`. |
| `/app/admin/network/page.tsx` | Redirect stub routing `/admin/network` to `/admin/users`. |
| `/app/admin/points/page.tsx` | Redirect stub routing `/admin/points` to `/admin/settings`. |
| `/app/admin/rewards/page.tsx` | Redirect stub routing `/admin/rewards` to `/admin/plans`. |
| `/app/api/admin/broadcast/route.ts` | Super Admin API endpoint for dispatching targeted broadcast notifications to users. |
| `/app/api/admin/ledger/route.ts` | Super Admin API endpoint returning platform-wide financial ledger entries. |
| `/app/api/admin/panel-images/route.ts` | Super Admin API endpoint for reading and updating solar panel marketing image URLs. |
| `/app/api/admin/recharges/route.ts` | Super Admin API endpoint for listing, approving, and rejecting user recharge deposit requests. |
| `/app/api/admin/rules/route.ts` | Super Admin API endpoint for viewing and updating system dynamic business rules. |
| `/app/api/admin/search/route.ts` | Super Admin API endpoint executing cross-entity searches across users, recharges, and withdrawals. |
| `/app/api/admin/stats/route.ts` | Super Admin API endpoint aggregating platform metrics, total generated energy, and cash reserves. |
| `/app/api/admin/units/route.ts` | Super Admin API endpoint returning all active, expired, and upgraded solar units in the fleet. |
| `/app/api/admin/users/route.ts` | Super Admin API endpoint for querying user lists and modifying user balances/roles/statuses. |
| `/app/api/admin/withdrawals/route.ts` | Super Admin API endpoint for querying withdrawal queues and executing status state transitions. |
| `/app/api/auth/login/route.ts` | Public authentication endpoint validating email/password credentials and establishing sessions. |
| `/app/api/auth/logout/route.ts` | Authenticated endpoint terminating user sessions and clearing authentication cookies. |
| `/app/api/auth/me/route.ts` | Authenticated endpoint returning current user profile data and handling profile updates. |
| `/app/api/auth/password/route.ts` | Authenticated endpoint updating user login password with bcrypt hashing and validation. |
| `/app/api/auth/sessions/route.ts` | Authenticated endpoint returning user active sessions and handling session revocation. |
| `/app/api/auth/signup/route.ts` | Public registration endpoint creating new users, assigning referral sponsor, and giving 70 points. |
| `/app/api/auth/transaction-password/route.ts` | Authenticated endpoint setting and verifying 6-digit transaction PIN with lockout protection. |
| `/app/api/dashboard/overview/route.ts` | Authenticated endpoint aggregating user balance, units, logs, ledger, and unread notifications. |
| `/app/api/leadership/progress/route.ts` | Authenticated endpoint evaluating user rank progress, team metrics, and promotion eligibility. |
| `/app/api/leadership/promote/route.ts` | Authenticated endpoint advancing user leadership rank and distributing rank bonuses. |
| `/app/api/mlm/stats/route.ts` | Public/unauthenticated endpoint returning user MLM downline stats (CRITICAL SECURITY GAP). |
| `/app/api/mlm/tree/route.ts` | Authenticated endpoint building 3-level hierarchical MLM downline visualization tree. |
| `/app/api/points/adjust/route.ts` | Super Admin endpoint executing manual points credit/debit with mandatory audit reason. |
| `/app/api/points/redeem/route.ts` | Authenticated endpoint processing milestone reward redemptions and points deductions. |
| `/app/api/recharge/list/route.ts` | Authenticated endpoint returning user's historical and pending recharge records. |
| `/app/api/recharge/submit/route.ts` | Authenticated endpoint accepting crypto deposit proofs and queueing them for admin review. |
| `/app/api/solar/operate/route.ts` | Authenticated endpoint executing daily solar generation cycle (START -> RECEIVE). |
| `/app/api/solar/plans/route.ts` | Dual-mode endpoint (public GET / Super Admin POST) for viewing and updating solar plans. |
| `/app/api/solar/purchase/route.ts` | Authenticated endpoint deducting wallet balance and provisioning a new solar unit. |
| `/app/api/solar/upgrade/route.ts` | Authenticated endpoint calculating trade-in value, deducting top-up, and upgrading a solar unit. |
| `/app/api/support/tickets/route.ts` | Authenticated endpoint creating and querying customer support tickets and message threads. |
| `/app/api/withdrawals/process/route.ts` | Super Admin endpoint processing withdrawal approvals, blockchain TX hashes, and refunds. |
| `/app/api/withdrawals/request/route.ts` | Authenticated endpoint validating transaction PIN, calculating fees, and creating withdrawal requests. |

---

## 1.2 Tech Stack Inventory

| Package Name | Installed Version | Production / Dev | Architectural Purpose | Status & Vulnerability Evaluation |
| :--- | :--- | :--- | :--- | :--- |
| `next` | `^14.2.23` (resolves `14.2.35`) | Production | Core full-stack React framework (App Router architecture, API route handlers, Server Components). | Stable Next.js 14 release. No known high-severity CVEs in active version. |
| `react` | `^18.3.1` | Production | Core UI rendering library. | Current stable React 18 production release. |
| `react-dom` | `^18.3.1` | Production | DOM renderer for React web application. | Matches `react` version. |
| `@supabase/ssr` | `^0.12.5` | Production | Server-side cookie-based authentication and session client for Next.js SSR. | Modern SSR package replacing deprecated `@supabase/auth-helpers-nextjs`. |
| `@supabase/supabase-js` | `^2.112.3` | Production | Official Supabase PostgreSQL client and authentication SDK. | Actively maintained; full support for Postgres RLS and Auth. |
| `bcryptjs` | `^3.0.3` | Production | Pure JavaScript implementation of bcrypt password hashing algorithm. | Secure for CPU password/PIN hashing without native build toolchains. |
| `canvas-confetti` | `^1.9.4` | Production | Canvas-based celebratory particle animations triggered upon yield receipt and promotions. | Client-side visual enhancement. |
| `clsx` | `^2.1.1` | Production | Utility for constructing conditional className strings efficiently. | Industry standard utility. |
| `tailwind-merge` | `^3.0.2` | Production | Utility to merge conflicting Tailwind CSS classes without stylesheet specificity bugs. | Compatible with custom theme tokens. |
| `date-fns` | `^4.1.0` | Production | Modern, modular date manipulation and formatting library. | Lightweight, immutable date handling. |
| `framer-motion` | `^12.4.7` | Production | Production-grade motion and gesture library for React glass animations. | Modern Framer Motion v12 release. |
| `lenis` | `^1.1.20` | Production | Smooth scrolling library providing luxury scrolling dynamics. | Provides fluid inertia-based viewport scrolling. |
| `lucide-react` | `^1.16.0` | Production | Comprehensive, scalable SVG icon library used across all dashboards. | Optimized tree-shakeable icon package. |
| `qrcode.react` | `^4.2.0` | Production | SVG/Canvas QR code generator for USDT TRC-20 deposit addresses and invite links. | Secure client-side QR renderer. |
| `react-hook-form` | `^7.54.2` | Production | Performant, flexible form validation library with minimal re-renders. | Used in profile and administrative forms. |
| `recharts` | `^2.15.1` | Production | Composable charting library built on React components and SVG. | Powers telemetry generation and financial analytics charts. |
| `zod` | `^3.24.2` | Production | TypeScript-first schema declaration and runtime validation library. | Used in route handlers for server-side payload validation. |
| `@types/bcryptjs` | `^2.4.6` | Development | TypeScript definitions for bcryptjs. | Development type safety. |
| `@types/canvas-confetti` | `^1.9.0` | Development | TypeScript definitions for canvas-confetti. | Development type safety. |
| `@types/dotenv` | `^6.1.1` | Development | TypeScript definitions for dotenv. | Development type safety. |
| `@types/node` | `^20.17.19` | Development | TypeScript definitions for Node.js runtime. | Node.js v20 LTS typings. |
| `@types/react` | `^18.3.18` | Development | TypeScript definitions for React. | Matches React 18 runtime. |
| `@types/react-dom` | `^18.3.5` | Development | TypeScript definitions for React DOM. | Matches React DOM 18 runtime. |
| `autoprefixer` | `^10.4.20` | Development | PostCSS plugin to parse CSS and add vendor prefixes. | Standard CSS build pipeline. |
| `dotenv` | `^17.4.2` | Development | Zero-dependency module that loads environment variables from `.env` files. | Used in seeding scripts. |
| `eslint` | `^8.57.0` | Development | JavaScript and TypeScript linting utility. | Stable ESLint v8. |
| `eslint-config-next` | `^14.2.23` | Development | Next.js specific ESLint rule configuration. | Enforces Next.js best practices and Core Web Vitals. |
| `postcss` | `^8.5.2` | Development | Tool for transforming styles with JS plugins. | Standard CSS processor. |
| `tailwindcss` | `^3.4.17` | Development | Utility-first CSS framework. | Version 3.4.17 with JIT engine. |
| `tsx` | `^4.23.12` | Development | TypeScript Execute: fast CLI for running TypeScript files directly. | Used in scripts and seeding routines. |
| `typescript` | `^5.7.3` | Development | TypeScript language compiler and type checker. | Current TypeScript v5 compiler. |
| `vitest` | `^3.0.5` | Development | Next-generation testing framework powered by Vite. | **CRITICAL ISSUE:** Startup failure due to CJS/ESM conflict in Vitest config with Vite. |

---

## 1.3 Build and Configuration Audit

### `next.config.mjs`
```javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "**",
      },
    ],
  },
};
export default nextConfig;
```
**Audit Analysis:**
1. **Risky Image Domain Wildcard (`hostname: "**"`):** Setting `hostname: "**"` allows Next.js image optimization proxy (`/_next/image`) to fetch and optimize images from any URL on the internet. This exposes the server to **Server-Side Request Forgery (SSRF)** and **Denial of Service (DoS)** through remote resource amplification.
   *Recommendation:* Restrict `remotePatterns` to trusted domains (e.g., `onkypgkyqjznksdbsxtp.supabase.co`, `images.unsplash.com`).
2. **Missing Security Headers:** `next.config.mjs` contains no custom headers. The application lacks essential HTTP security headers:
   - `Content-Security-Policy` (CSP)
   - `X-Frame-Options: DENY` (Clickjacking defense)
   - `X-Content-Type-Options: nosniff` (MIME sniffing defense)
   - `Referrer-Policy: strict-origin-when-cross-origin`
   - `Permissions-Policy` (Restricting camera, microphone, geolocation)
   - `Strict-Transport-Security` (HSTS: `max-age=63072000; includeSubDomains; preload`)

### `tailwind.config.ts`
**Audit Analysis:**
- Defines a comprehensive `solar` color palette based on Midnight Navy (`#050B18`, `#070E1C`, `#0B1426`, `#111E38`) and Solar Gold (`#FFC83D`, `#FF9F1C`, `#3B82F6`).
- Extends typography with `Inter` (sans), `JetBrains Mono` (mono), and `Outfit` (display).
- Configures custom radial gradients, grid backgrounds, and glow box shadows.
- Dark mode is configured via class (`darkMode: "class"`), and root HTML defaults to `dark`.

### `tsconfig.json`
**Audit Analysis:**
- Compiler options enforce `"strict": true`, `"moduleResolution": "bundler"`, and `"skipLibCheck": true`.
- Path aliases map `@/*` to `./*`.
- **Finding:** `npx tsc --noEmit` produces errors in `lib/database/seed-data.ts` due to missing properties on `SolarUnit` mock objects.

### `middleware.ts` & `lib/supabase/middleware.ts`
**Audit Analysis:**
- Uses `@supabase/ssr` `createServerClient` to refresh session cookies on incoming requests.
- Protects `/admin` and `/api/admin` routes by checking if a Supabase user session exists.
- **Critical Architectural Defect in Middleware:** `lib/supabase/middleware.ts` line 66 only checks `if (!user)`! It does **not** verify whether the authenticated user has the `SUPER_ADMIN` role! Consequently, any normal authenticated member can bypass Edge middleware and access `/admin/*` pages in the browser unless individual pages or API endpoints perform an explicit secondary role check.

### `vitest.config.ts`
**Audit Analysis:**
- Configured with `environment: "node"`, `globals: true`, and path alias `@/`.
- **Critical Build Failure:** Executing `npm test` fails immediately with `[ERR_REQUIRE_ESM]` because `vitest/dist/config.cjs` attempts a synchronous `require()` of Vite's ESM entry point.

---

## 1.4 Environment Variable (`.env`) Audit

| Variable Name | Defined In `.env` | Referenced In Code | Client Exposed (`NEXT_PUBLIC_`) | Safe for Client? | Fallback Present in Code? | Security Assessment & Finding |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| `NEXT_PUBLIC_APP_NAME` | `"SolarGrid"` | `lib/supabase/middleware.ts`, `app/layout.tsx` | Yes | Yes | Yes (`'SolarGrid'`) | Safe UI branding constant. |
| `NEXT_PUBLIC_APP_URL` | `"http://localhost:3000"` | `app/api/auth/*` | Yes | Yes | Yes (`'http://localhost:3000'`) | Public origin URL. Must be updated to production domain in deployment. |
| `NEXT_PUBLIC_SITE_TITLE` | `"SolarGrid \| Digital..."` | `app/layout.tsx` | Yes | Yes | Yes | Safe SEO meta string. |
| `NEXT_PUBLIC_SUPABASE_URL` | `"https://onkypgkyqjznksdbsxtp.supabase.co"` | `lib/supabase/*`, `scripts/*` | Yes | Yes | Yes (Hardcoded in `db.ts`, `server.ts`) | **HIGH RISK HARDCODING:** If `.env` is missing, code falls back to a live Supabase URL. |
| `NEXT_PUBLIC_SUPABASE_ANON_KEY` | `"eyJhbGciOiJIUzI1NiIsInR5cCI6..."` | `lib/supabase/*`, `scripts/*` | Yes | Yes (Intended for public RLS access) | Yes (Hardcoded in `middleware.ts`, `server.ts`) | **CRITICAL SECURITY RISK:** Hardcoded JWT anon key in source code (`lib/supabase/server.ts` line 5, `lib/supabase/middleware.ts` line 5). |
| `SUPABASE_SERVICE_ROLE_KEY` | `"eyJhbGciOiJIUzI1NiIsInR5cCI6..."` | `lib/supabase/admin.ts`, `scripts/*` | **NO** (Server Only) | **FATAL IF EXPOSED** | No (Throws error if missing) | **CRITICAL SECURITY RISK:** Live Supabase Service Role key (which completely bypasses RLS and grants full database admin access) is stored in plaintext in `.env` committed to repository. Must be rotated immediately in Supabase Console. |
| `DEFAULT_STARTING_POINTS` | `70` | `lib/points-engine/*`, `lib/supabase/db.ts` | No | Yes | Yes (`70`) | Safe numeric business constant. |
| `WORKING_DAYS_PER_CYCLE` | `43` | `lib/solar-engine/*`, `lib/supabase/db.ts` | No | Yes | Yes (`43`) | Safe numeric business constant. |
| `DEFAULT_CYCLE_CALENDAR_DAYS` | `60` | `lib/solar-engine/*`, `lib/supabase/db.ts` | No | Yes | Yes (`60`) | Safe numeric business constant. |

"""
